Repository karydia/karydia, pull requests merged in 2019-10, with the labels that each got.

#215 Move karydia to namespace "karydia"
  Makefile
  docs/manualInstallation.md
  install/README.md
  install/charts/templates/configure-karydia-webhook.sh.tpl
  install/charts/templates/create-karydia-certificate.sh.tpl
  install/charts/templates/create-karydia-tls-secret.sh.tpl
  install/charts/templates/delete-clean-up.yaml
  install/charts/templates/karydia-namespace.yaml
  install/charts/templates/workaround-annotate-kube-system-namespace.yaml
  install/charts/values.yaml
  tests/e2e/admission_seccomp_test.go
  tests/e2e/admission_security_context_test.go
Labels: help wanted, review wanted

#222 Language editing for readme.md
  README.md
Labels: bug fix, review wanted

#227 Use the "--namespace" CLI flag
  README.md
  docs/manualInstallation.md
  install/README.md
  install/charts/templates/configmap.yaml
  install/charts/templates/configure-karydia-webhook.sh.tpl
  install/charts/templates/create-karydia-certificate.sh.tpl
  install/charts/templates/create-karydia-tls-secret.sh.tpl
  install/charts/templates/custom-seccomp-daemonset.yaml
  install/charts/templates/custom-seccomp-profiles.yaml
  install/charts/templates/delete-clean-up.yaml
  install/charts/templates/deployment.yaml
  install/charts/templates/karydia-namespace.yaml
  install/charts/templates/post-install-webhook.yaml
  install/charts/templates/rbac.yaml
  install/charts/templates/service.yaml
  install/charts/templates/workaround-annotate-kube-system-namespace.yaml
  install/charts/values.yaml
Labels: bug fix, review wanted

#233 Update Deployment Accordingly Kubernetes Version 1.16
  Dockerfile
  install/charts/templates/deployment.yaml
Labels: bug fix, review wanted

#237 Re-add Option to Increase Timeout
  install/charts/templates/deployment.yaml
Labels: review wanted
