Repository karydia/karydia, pull requests merged in 2019-03, with the labels that each got.

#63 Fix deployment-dev generator for linux
  scripts/generate-deployment-dev
Labels: bug

#64 Switch to ONE multistage Dockerfile & adjust hotswap documentation
  Dockerfile
  Dockerfile.dev
  Makefile
  docs/devel/hotswap.md
Labels: enhancement

#65 [CI] Run build and unit-tests for pull-requests
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test
