Repository karydia/karydia, pull requests merged in 2019-05, with the labels that each got.

#105 Increase waiting timeout
  docs/devel/hotswap.md
  manifests-dev/deployment-dev.yml
  scripts/hotswap-dev
Labels: review wanted

#109 Fix possible deadlock
  docs/devel/hotswap.md
  scripts/hotswap-dev
Labels: bug fix, review wanted

#107 Change default behavior of ServiceAcounnts automount to false
  contrib/gardener/scripts/configure-karydia-webhook-cp
  docs/features.md
  pkg/admission/karydia/karydia.go
  pkg/admission/karydia/pod_admission.go
  pkg/admission/karydia/service_account_admission.go
  pkg/admission/karydia/service_token_test.go
  scripts/configure-karydia-webhook
  tests/e2e/framework/framework.go
  tests/e2e/karydia_admission_test.go
Labels: enhancement, review wanted

#112 Employ patch structure for mutation
  pkg/admission/karydia/karydia.go
  pkg/admission/karydia/pod_admission.go
  pkg/admission/karydia/seccomp_test.go
  pkg/admission/karydia/service_account_admission.go
  pkg/admission/karydia/service_token_test.go
  pkg/k8sutil/admission.go
Labels: enhancement, review wanted

#114 Consistent filenames for admission
  pkg/admission/karydia/admission.go
  pkg/admission/karydia/admission_pod.go
  pkg/admission/karydia/admission_service_account.go
Labels: review wanted

#113 Add the possibility to have multiple default network policies.
  pkg/controller/networkpolicy_reconciler.go
Labels: review wanted

#117 [Test] Integration of seccomp admission
  docs/features.md
  pkg/admission/karydia/admission_pod.go
  pkg/admission/karydia/seccomp_test.go
  tests/e2e/admission_automount_token_test.go
  tests/e2e/admission_seccomp_test.go
Labels: review wanted, tests

#116 Fix error handling.
  pkg/controller/networkpolicy_reconciler.go
Labels: review wanted

#122 [Test] Coverage of admission package
  pkg/admission/karydia/admission.go
  pkg/admission/karydia/admission_test.go
Labels: review wanted

#123 Make goal to meter test coverage
  .gitignore
  Makefile
Labels: review wanted

#120 Use current image for deployement
  Makefile
  contrib/gardener/scripts/deploy-karydia-cp
  docs/devel/hotswap.md
  docs/install.md
  manifests/deployment.yml
  tests/e2e/framework/framework.go
Labels: bug fix, review wanted

#127 Karydia config tests
  pkg/controller/config_reconciler.go
  pkg/controller/networkpolicy_reconciler_test.go
Labels: review wanted

#131 Fix nil pointer issue after restart of pod
  cli/cmd/runserver.go
  pkg/controller/networkpolicy_reconciler.go
  pkg/controller/networkpolicy_reconciler_test.go
Labels: bug fix

#136 Add karydia config integration tests
  tests/e2e/admission_automount_token_test.go
  tests/e2e/admission_seccomp_test.go
  tests/e2e/framework/framework.go
Labels: enhancement, review wanted
