Repository karydia/karydia, pull requests merged in 2019-08, with the labels that each got.

#168 Documentation: Describe how to enable/disable each feature separately
  docs/features.md
Labels: review wanted

#178 Readme features
  README.md
  docs/images/networkpolicy.png
  docs/images/pod-with-karydia.png
  docs/images/pod-without-karydia.png
Labels: review wanted

#186 [GOLANG] version bump to 1.12.8
  Dockerfile
Labels: review wanted

#187 [WORKAROUND] #183
  install/charts/templates/workaround-annotate-kube-system-namespace.yaml
Labels: review wanted

#190 [LOGGING] Unification
  .dockerignore
  .gitignore
  Dockerfile
  Gopkg.lock
  Gopkg.toml
  NOTICE.md
  cli/cmd/root.go
  cli/cmd/runserver.go
  cli/cmd/version.go
  cli/main.go
  install/charts/templates/deployment.yaml
  install/charts/values.yaml
  pkg/admission/interface.go
  pkg/admission/karydia/admission.go
  pkg/admission/karydia/admission_test.go
  pkg/admission/karydia/seccomp_test.go
  pkg/admission/karydia/service_token_test.go
  pkg/apis/karydia/register.go
  pkg/controller/config_reconciler.go
  pkg/controller/networkpolicy_reconciler.go
  pkg/controller/networkpolicy_reconciler_test.go
  pkg/k8sutil/authorizer.go
  pkg/k8sutil/clientset.go
  pkg/logger/logger.go
  pkg/server/server.go
  pkg/util/tls/tls.go
  pkg/webhook/webhook.go
  scripts/configure-karydia-webhook
  scripts/create-karydia-certificate
  scripts/create-karydia-tls-secret
  scripts/hotswap-dev
  tests/e2e/admission_automount_token_test.go
  tests/e2e/admission_seccomp_test.go
  tests/e2e/admission_security_context_test.go
  tests/e2e/framework/framework.go
  tests/e2e/karydia_default_network_policy_test.go
  tests/e2e/karydia_network_policy_reconciler_test.go
  tests/e2e/main_test.go
  version.go
Labels: review wanted

#192 [GOLANG] version bump to 1.12.9
  Dockerfile
Labels: review wanted

#193 [DEPENDENCY] version bumps
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/utils/trace/trace.go
Labels: review wanted

#191 Update codegen
  .dockerignore
  .gitignore
  contrib/gardener/manifests/rbac-cp.yml
  contrib/gardener/scripts/configure-karydia-webhook-cp
  contrib/gardener/scripts/create-karydia-kubeconfig-cp
  contrib/gardener/scripts/deploy-karydia-cp
  docs/development-and-gardener-setup.md
  hack/tools.go
  hack/update-codegen.sh
  hack/verify-codegen.sh
Labels: review wanted

#194 Update ignore files
  .dockerignore
  .gitignore
Labels: review wanted

#179 Internal karydia feature annotations for network policies
  docs/features.md
  pkg/controller/networkpolicy_reconciler.go
  pkg/controller/networkpolicy_reconciler_test.go
Labels: review wanted

#180 Delete outdated network policy if annotation is added
  install/charts/templates/rbac.yaml
  pkg/controller/networkpolicy_reconciler.go
  pkg/controller/networkpolicy_reconciler_test.go
  tests/e2e/karydia_network_policy_reconciler_test.go
Labels: bug fix, review wanted

#198 Update workaround's hyperkube version
  install/charts/templates/workaround-annotate-kube-system-namespace.yaml
Labels: review wanted

#200 Remove "Clone Repository" instructions from install readme
  install/README.md
Labels: enhancement, review wanted

#201 Add Documentation for Manual Install Process
  docs/manualInstallation.md
  install/README.md
Labels: enhancement, review wanted

#199 Remove CRDs and webhooks on delete
  install/charts/templates/delete-clean-up.yaml
Labels: bug fix, review wanted

#205 Add option to enforce specified default karydia config
  cli/cmd/runserver.go
  install/charts/templates/config.yaml
  install/charts/templates/crd-config.yaml
  install/charts/values.yaml
  pkg/admission/karydia/admission_pod.go
  pkg/admission/karydia/admission_service_account.go
  pkg/apis/karydia/v1alpha1/types.go
  pkg/controller/config_reconciler.go
  pkg/controller/networkpolicy_reconciler.go
  pkg/controller/networkpolicy_reconciler_test.go
Labels: review wanted

#207 Withdraw 'kube-system' namespace from enforcement
  install/charts/templates/workaround-annotate-kube-system-namespace.yaml
  pkg/admission/karydia/admission_pod.go
  pkg/admission/karydia/admission_service_account.go
Labels: review wanted

#206 [ALPINE] version bump to 3.10.2
  Dockerfile
Labels: review wanted

#208 User kubeconfig example
  .dockerignore
  .gitignore
  scripts/create-user-kubeconfig-example
Labels: review wanted
