Repository karydia/karydia, pull requests merged in 2019-04, with the labels that each got.

#75 Issue templates added and pull request template adjusted
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement, needs/ok-to-test

#66 Mutate service token pod webhook
  docs/features.md
  pkg/admission/karydia/karydia.go
  pkg/admission/karydia/karydia_test.go
  pkg/admission/karydiasecuritypolicy/pod_seccomp_test.go
  pkg/admission/karydiasecuritypolicy/pod_service_token_test.go
  pkg/k8sutil/admission.go
  tests/e2e/karydia_admission_test.go
Labels: enhancement, needs/ok-to-test

#86 Enrich hotswap with ability to handle debugging
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  docs/devel/hotswap.md
  manifests-dev/deployment-dev.yml
  scripts/generate-deployment-dev
  scripts/hotswap-dev
Labels: enhancement, needs/ok-to-test

#84 Distinguish between mutating and validating service token pod webhook.
  pkg/admission/karydia/karydia.go
  pkg/admission/karydia/service_token_test.go
Labels: bug, needs/ok-to-test

#85 [Test] E2E tests for service token pod webhook
  tests/e2e/framework/framework.go
  tests/e2e/karydia_admission_test.go
Labels: enhancement, needs/ok-to-test

#87 Remove option to enable KSP admission feature.
  cli/cmd/runserver.go
Labels: needs/ok-to-test, question

#82 manifests/rbac: allow karydia to list {cluster,}role{s,bindings}
  manifests/rbac.yml
Labels: bug, needs/ok-to-test

#90 [FIX] Fix bug for remove-default option for admission hook caused by #84
  pkg/admission/karydia/karydia.go
  pkg/admission/karydia/service_token_test.go
Labels: bug, review wanted

#91 Enhance pull request template
  .github/pull_request_template.md
Labels: enhancement, review wanted

#93 Distinguish between mutating and validating service token pod webhook
  pkg/admission/karydia/karydia.go
  pkg/admission/karydia/service_token_test.go
Labels: bug fix, review wanted

#94 Enhance templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
Labels: enhancement, review wanted

#95 Fixed internal error when pod has no annotation
  pkg/admission/karydiasecuritypolicy/pod.go
  pkg/admission/karydiasecuritypolicy/pod_seccomp_test.go
Labels: bug fix, review wanted

#100 Separate logic of pod mutation and validation web-hook
  pkg/admission/karydia/karydia.go
  pkg/admission/karydia/seccomp_test.go
  pkg/admission/karydia/service_token_test.go
  pkg/k8sutil/admission.go
  tests/e2e/framework/framework.go
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/merge_test.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
Labels: review wanted

#103 'Makefile' adjustment for new container-dev image name
  Makefile
Labels: review wanted
